### PR TITLE
При выключении guest pass terminal из сети его спрайт исчезал.

### PR DESCRIPTION
**Pull request by RichardJones1**
:cl: Richard Jones
 - bugfix: спрайт guest pass terminal меняется, если энергии нет.

### CODE REVIEW

**Comment by TauKitty** [comment]
## DMI Diff Report

<details><summary>icons/obj/computer.dmi <b><< duplicates</b></summary><hr>

**Warning!** States duplication detected:
- **Old DMI:** [teleport0, tank0, teleportb, teleport, tankb, guest]
- **New DMI:** [teleport0, tank0, teleportb, teleport, tankb, guest]

*Duplication of states may result into unpredictable behavior in game and incorrect diff report, so fix is recommended.*

Key|Dir / Frame|Old|New|Status
---|:---------:|---|---|------
oldcomp0 ([x1](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/32x32/forceresize/1iyrv130tb.png&after=https://img.taucetistation.org/32x32/forceresize/racffdk42o.png) [x4](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/128x128/forceresize/1iyrv130tb.png&after=https://img.taucetistation.org/128x128/forceresize/racffdk42o.png) [x8](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/256x256/forceresize/1iyrv130tb.png&after=https://img.taucetistation.org/256x256/forceresize/racffdk42o.png))|🡻 S / 1|||Modified
tcstationb ([x1](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/32x32/forceresize/suq59e2v3a.png&after=https://img.taucetistation.org/32x32/forceresize/60fev7to90.png) [x4](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/128x128/forceresize/suq59e2v3a.png&after=https://img.taucetistation.org/128x128/forceresize/60fev7to90.png) [x8](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/256x256/forceresize/suq59e2v3a.png&after=https://img.taucetistation.org/256x256/forceresize/60fev7to90.png))|🡻 S / 1|||Modified
tcbossb ([x1](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/32x32/forceresize/buu7ovl3xg.png&after=https://img.taucetistation.org/32x32/forceresize/ry0ae93sh4.png) [x4](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/128x128/forceresize/buu7ovl3xg.png&after=https://img.taucetistation.org/128x128/forceresize/ry0ae93sh4.png) [x8](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/256x256/forceresize/buu7ovl3xg.png&after=https://img.taucetistation.org/256x256/forceresize/ry0ae93sh4.png))|🡻 S / 1|||Modified
oldcompb ([x1](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/32x32/forceresize/z10jz06i2n.png&after=https://img.taucetistation.org/32x32/forceresize/1iyrv130tb.png) [x4](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/128x128/forceresize/z10jz06i2n.png&after=https://img.taucetistation.org/128x128/forceresize/1iyrv130tb.png) [x8](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/256x256/forceresize/z10jz06i2n.png&after=https://img.taucetistation.org/256x256/forceresize/1iyrv130tb.png))|🡻 S / 1|||Modified
erokez ([x1](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/32x32/forceresize/ufb228dm4i.png&after=https://img.taucetistation.org/32x32/forceresize/bcbfbjp13l.png) [x4](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/128x128/forceresize/ufb228dm4i.png&after=https://img.taucetistation.org/128x128/forceresize/bcbfbjp13l.png) [x8](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/256x256/forceresize/ufb228dm4i.png&after=https://img.taucetistation.org/256x256/forceresize/bcbfbjp13l.png))|🡻 S / 1|||Modified
erokez ([x1](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/32x32/forceresize/bcbfbjp13l.png&after=https://img.taucetistation.org/32x32/forceresize/n8v3ew17a5.png) [x4](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/128x128/forceresize/bcbfbjp13l.png&after=https://img.taucetistation.org/128x128/forceresize/n8v3ew17a5.png) [x8](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/256x256/forceresize/bcbfbjp13l.png&after=https://img.taucetistation.org/256x256/forceresize/n8v3ew17a5.png))|🡻 S / 2|||Modified
Cockpit ([x1](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/32x32/forceresize/sxp0e6lgam.png&after=https://img.taucetistation.org/32x32/forceresize/yoglx2pwd3.png) [x4](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/128x128/forceresize/sxp0e6lgam.png&after=https://img.taucetistation.org/128x128/forceresize/yoglx2pwd3.png) [x8](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/256x256/forceresize/sxp0e6lgam.png&after=https://img.taucetistation.org/256x256/forceresize/yoglx2pwd3.png))|🡻 S / 1|||Modified
oldcomp ([x1](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/32x32/forceresize/kylse0czso.png&after=https://img.taucetistation.org/32x32/forceresize/z10jz06i2n.png) [x4](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/128x128/forceresize/kylse0czso.png&after=https://img.taucetistation.org/128x128/forceresize/z10jz06i2n.png) [x8](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/256x256/forceresize/kylse0czso.png&after=https://img.taucetistation.org/256x256/forceresize/z10jz06i2n.png))|🡻 S / 1|||Modified
tcboss0 ([x1](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/32x32/forceresize/zmezflf7w3.png&after=https://img.taucetistation.org/32x32/forceresize/buu7ovl3xg.png) [x4](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/128x128/forceresize/zmezflf7w3.png&after=https://img.taucetistation.org/128x128/forceresize/buu7ovl3xg.png) [x8](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/256x256/forceresize/zmezflf7w3.png&after=https://img.taucetistation.org/256x256/forceresize/buu7ovl3xg.png))|🡻 S / 1|||Modified
erokez0 ([x1](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/32x32/forceresize/yoglx2pwd3.png&after=https://img.taucetistation.org/32x32/forceresize/kkywtkvonq.png) [x4](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/128x128/forceresize/yoglx2pwd3.png&after=https://img.taucetistation.org/128x128/forceresize/kkywtkvonq.png) [x8](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/256x256/forceresize/yoglx2pwd3.png&after=https://img.taucetistation.org/256x256/forceresize/kkywtkvonq.png))|🡻 S / 1|||Modified
tcstation-closed ([x1](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/32x32/forceresize/60fev7to90.png&after=https://img.taucetistation.org/32x32/forceresize/tlqhi98u2u.png) [x4](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/128x128/forceresize/60fev7to90.png&after=https://img.taucetistation.org/128x128/forceresize/tlqhi98u2u.png) [x8](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/256x256/forceresize/60fev7to90.png&after=https://img.taucetistation.org/256x256/forceresize/tlqhi98u2u.png))|🡻 S / 1|||Modified
wagon0 ([x1](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/32x32/forceresize/soo3qt7z9n.png&after=https://img.taucetistation.org/32x32/forceresize/sxp0e6lgam.png) [x4](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/128x128/forceresize/soo3qt7z9n.png&after=https://img.taucetistation.org/128x128/forceresize/sxp0e6lgam.png) [x8](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/256x256/forceresize/soo3qt7z9n.png&after=https://img.taucetistation.org/256x256/forceresize/sxp0e6lgam.png))|🡻 S / 1|||Modified
tcstation0 ([x1](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/32x32/forceresize/mlrezqzinu.png&after=https://img.taucetistation.org/32x32/forceresize/suq59e2v3a.png) [x4](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/128x128/forceresize/mlrezqzinu.png&after=https://img.taucetistation.org/128x128/forceresize/suq59e2v3a.png) [x8](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/256x256/forceresize/mlrezqzinu.png&after=https://img.taucetistation.org/256x256/forceresize/suq59e2v3a.png))|🡻 S / 1|||Modified
erokezzb ([x1](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/32x32/forceresize/t9gndl451b.png&after=https://img.taucetistation.org/32x32/forceresize/kylse0czso.png) [x4](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/128x128/forceresize/t9gndl451b.png&after=https://img.taucetistation.org/128x128/forceresize/kylse0czso.png) [x8](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/256x256/forceresize/t9gndl451b.png&after=https://img.taucetistation.org/256x256/forceresize/kylse0czso.png))|🡻 S / 1|||Modified
wagon ([x1](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/32x32/forceresize/0yy5gas97f.png&after=https://img.taucetistation.org/32x32/forceresize/oo2yl9h0m3.png) [x4](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/128x128/forceresize/0yy5gas97f.png&after=https://img.taucetistation.org/128x128/forceresize/oo2yl9h0m3.png) [x8](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/256x256/forceresize/0yy5gas97f.png&after=https://img.taucetistation.org/256x256/forceresize/oo2yl9h0m3.png))|🡻 S / 1|||Modified
erokezb ([x1](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/32x32/forceresize/4etd1i62cx.png&after=https://img.taucetistation.org/32x32/forceresize/t9gndl451b.png) [x4](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/128x128/forceresize/4etd1i62cx.png&after=https://img.taucetistation.org/128x128/forceresize/t9gndl451b.png) [x8](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/256x256/forceresize/4etd1i62cx.png&after=https://img.taucetistation.org/256x256/forceresize/t9gndl451b.png))|🡻 S / 1|||Modified
tcboss ([x1](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/32x32/forceresize/tlqhi98u2u.png&after=https://img.taucetistation.org/32x32/forceresize/zmezflf7w3.png) [x4](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/128x128/forceresize/tlqhi98u2u.png&after=https://img.taucetistation.org/128x128/forceresize/zmezflf7w3.png) [x8](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/256x256/forceresize/tlqhi98u2u.png&after=https://img.taucetistation.org/256x256/forceresize/zmezflf7w3.png))|🡻 S / 1|||Modified
erokezz ([x1](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/32x32/forceresize/n8v3ew17a5.png&after=https://img.taucetistation.org/32x32/forceresize/q3gu13p4og.png) [x4](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/128x128/forceresize/n8v3ew17a5.png&after=https://img.taucetistation.org/128x128/forceresize/q3gu13p4og.png) [x8](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/256x256/forceresize/n8v3ew17a5.png&after=https://img.taucetistation.org/256x256/forceresize/q3gu13p4og.png))|🡻 S / 1|||Modified
erokezz ([x1](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/32x32/forceresize/q3gu13p4og.png&after=https://img.taucetistation.org/32x32/forceresize/4etd1i62cx.png) [x4](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/128x128/forceresize/q3gu13p4og.png&after=https://img.taucetistation.org/128x128/forceresize/4etd1i62cx.png) [x8](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/256x256/forceresize/q3gu13p4og.png&after=https://img.taucetistation.org/256x256/forceresize/4etd1i62cx.png))|🡻 S / 2|||Modified
tcstation ([x1](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/32x32/forceresize/racffdk42o.png&after=https://img.taucetistation.org/32x32/forceresize/mlrezqzinu.png) [x4](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/128x128/forceresize/racffdk42o.png&after=https://img.taucetistation.org/128x128/forceresize/mlrezqzinu.png) [x8](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/256x256/forceresize/racffdk42o.png&after=https://img.taucetistation.org/256x256/forceresize/mlrezqzinu.png))|🡻 S / 1|||Modified
erokezz0 ([x1](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/32x32/forceresize/kkywtkvonq.png&after=https://img.taucetistation.org/32x32/forceresize/ufb228dm4i.png) [x4](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/128x128/forceresize/kkywtkvonq.png&after=https://img.taucetistation.org/128x128/forceresize/ufb228dm4i.png) [x8](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/256x256/forceresize/kkywtkvonq.png&after=https://img.taucetistation.org/256x256/forceresize/ufb228dm4i.png))|🡻 S / 1|||Modified
wagonb ([x1](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/32x32/forceresize/oo2yl9h0m3.png&after=https://img.taucetistation.org/32x32/forceresize/soo3qt7z9n.png) [x4](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/128x128/forceresize/oo2yl9h0m3.png&after=https://img.taucetistation.org/128x128/forceresize/soo3qt7z9n.png) [x8](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/256x256/forceresize/oo2yl9h0m3.png&after=https://img.taucetistation.org/256x256/forceresize/soo3qt7z9n.png))|🡻 S / 1|||Modified
guest0 ([x1](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/32x32/forceresize/0yy5gas97f.png) [x4](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/128x128/forceresize/0yy5gas97f.png) [x8](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/256x256/forceresize/0yy5gas97f.png))|🡻 S / 1|||Created

States number:
- **Old DMI:** 183
- **New DMI:** 184
<hr></details>

**Comment by AgRevol** [comment]
Меня пугает ДМИшный бот

**Comment by RichardJones1** [comment]
Меня тоже, у меня совсем другие изменения. Я переименовал всего лишь один спрайт.
из guest в guest0

**Comment by RichardJones1** [comment]
Кстати, он хорош тем, что показал дубликаты. Сейчас почищу их заодно.

**Comment by Belfogor** [comment]
Карл, у него спрайта в режиме "выключен" не было. Он просто исчезал нах*й.

**Comment by RichardJones1** [comment]
Ну, короче, я пофиксил. Там просто надо было переименовать спрайт один и всё.

**Comment by SpaiR** [comment]
> Меня пугает ДМИшный бот

У него сейчас баг, если в дми изначально были дубликаты диф будет некорректным. Так что смотрите вкладку `Checks`

image

**Comment by RichardJones1** [comment]
Спасибо

**Pull request merged**
