### PR TITLE
noslip

### PR DESCRIPTION
**Pull request by volas**
## Описание изменений

Подскальзывание отключено по техническим причинам

### CODE REVIEW

**Comment by TauKitty** [comment]
###### Changelog status: :radio_button: No changelog

**Comment by TauKitty** [comment]
This pull request has been mentioned on **Tau Ceti Station Forum**. There might be relevant details there:

https://forum.taucetistation.org/t/skrinshoty-iz-space-station-13/3165/12306

**Comment by TauKitty** [comment]
This pull request has been mentioned on **Tau Ceti Station Forum**. There might be relevant details there:

https://forum.taucetistation.org/t/knoka-ot-bananov-i-t-d/24358/2

**Comment by KIBORG04** [comment]
Хм, а если просто скопировать код слипов с тг, то все ли починится?

**Pull request closed without merging**
