### PR TITLE
Cigarettes resprite by WalterJe

### PR DESCRIPTION
**Pull request by YulianR**
tivw5yk

:cl: WalterJe
- image: Все станционные пачки сигарет изменены на новые с новыми спрайтами и названиями.

### CODE REVIEW

**Comment by TauKitty** [comment]
## DMI Diff Report

<details><summary>icons/obj/cigarettes.dmi</summary><hr />

Key | Dir / Frame | Old | New | Status
--- | :---------: | --- | --- | ------
Dpacket (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/c5tb08bp3y.png&after=http://img.taucetistation.org/32x32/forceresize/um4buh2q4j.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/c5tb08bp3y.png&after=http://img.taucetistation.org/128x128/forceresize/um4buh2q4j.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/c5tb08bp3y.png&after=http://img.taucetistation.org/256x256/forceresize/um4buh2q4j.png">x8</a>)|&#x1F87B; S / 1|||Modified
Dpacket1 (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/vphggidl97.png&after=http://img.taucetistation.org/32x32/forceresize/cyh27v6nbt.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/vphggidl97.png&after=http://img.taucetistation.org/128x128/forceresize/cyh27v6nbt.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/vphggidl97.png&after=http://img.taucetistation.org/256x256/forceresize/cyh27v6nbt.png">x8</a>)|&#x1F87B; S / 1|||Modified
cigpacket (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/ei81h2x5ii.png&after=http://img.taucetistation.org/32x32/forceresize/q6n82miuw6.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/ei81h2x5ii.png&after=http://img.taucetistation.org/128x128/forceresize/q6n82miuw6.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/ei81h2x5ii.png&after=http://img.taucetistation.org/256x256/forceresize/q6n82miuw6.png">x8</a>)|&#x1F87B; S / 1|||Modified
Dpacket0 (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/z3qu03glp3.png&after=http://img.taucetistation.org/32x32/forceresize/eksxcfii5p.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/z3qu03glp3.png&after=http://img.taucetistation.org/128x128/forceresize/eksxcfii5p.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/z3qu03glp3.png&after=http://img.taucetistation.org/256x256/forceresize/eksxcfii5p.png">x8</a>)|&#x1F87B; S / 1|||Modified
Dpacket3 (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/g0ztp21dyc.png&after=http://img.taucetistation.org/32x32/forceresize/c2yznulku0.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/g0ztp21dyc.png&after=http://img.taucetistation.org/128x128/forceresize/c2yznulku0.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/g0ztp21dyc.png&after=http://img.taucetistation.org/256x256/forceresize/c2yznulku0.png">x8</a>)|&#x1F87B; S / 1|||Modified
Dpacket2 (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/tx7z7gdo4q.png&after=http://img.taucetistation.org/32x32/forceresize/vf7dqsdxus.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/tx7z7gdo4q.png&after=http://img.taucetistation.org/128x128/forceresize/vf7dqsdxus.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/tx7z7gdo4q.png&after=http://img.taucetistation.org/256x256/forceresize/vf7dqsdxus.png">x8</a>)|&#x1F87B; S / 1|||Modified
ucig6 (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/4q8hksmi7t.png&after=http://img.taucetistation.org/32x32/forceresize/0cwnt06dd3.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/4q8hksmi7t.png&after=http://img.taucetistation.org/128x128/forceresize/0cwnt06dd3.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/4q8hksmi7t.png&after=http://img.taucetistation.org/256x256/forceresize/0cwnt06dd3.png">x8</a>)|&#x1F87B; S / 1|||Modified
ucig5 (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/6udd1yq4la.png&after=http://img.taucetistation.org/32x32/forceresize/b76ooqvukt.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/6udd1yq4la.png&after=http://img.taucetistation.org/128x128/forceresize/b76ooqvukt.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/6udd1yq4la.png&after=http://img.taucetistation.org/256x256/forceresize/b76ooqvukt.png">x8</a>)|&#x1F87B; S / 1|||Modified
ucig4 (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/swg66swbx1.png&after=http://img.taucetistation.org/32x32/forceresize/uis90s5jem.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/swg66swbx1.png&after=http://img.taucetistation.org/128x128/forceresize/uis90s5jem.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/swg66swbx1.png&after=http://img.taucetistation.org/256x256/forceresize/uis90s5jem.png">x8</a>)|&#x1F87B; S / 1|||Modified
syndie4 (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/i7q4ctrgld.png&after=http://img.taucetistation.org/32x32/forceresize/4fogadnm9o.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/i7q4ctrgld.png&after=http://img.taucetistation.org/128x128/forceresize/4fogadnm9o.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/i7q4ctrgld.png&after=http://img.taucetistation.org/256x256/forceresize/4fogadnm9o.png">x8</a>)|&#x1F87B; S / 1|||Modified
ucig3 (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/jlbykm441o.png&after=http://img.taucetistation.org/32x32/forceresize/owpowi7ldc.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/jlbykm441o.png&after=http://img.taucetistation.org/128x128/forceresize/owpowi7ldc.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/jlbykm441o.png&after=http://img.taucetistation.org/256x256/forceresize/owpowi7ldc.png">x8</a>)|&#x1F87B; S / 1|||Modified
syndie5 (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/zv6xe07nif.png&after=http://img.taucetistation.org/32x32/forceresize/s4bcaqqc6n.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/zv6xe07nif.png&after=http://img.taucetistation.org/128x128/forceresize/s4bcaqqc6n.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/zv6xe07nif.png&after=http://img.taucetistation.org/256x256/forceresize/s4bcaqqc6n.png">x8</a>)|&#x1F87B; S / 1|||Modified
ucig2 (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/rrh6cd761f.png&after=http://img.taucetistation.org/32x32/forceresize/5t3v5k6k4o.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/rrh6cd761f.png&after=http://img.taucetistation.org/128x128/forceresize/5t3v5k6k4o.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/rrh6cd761f.png&after=http://img.taucetistation.org/256x256/forceresize/5t3v5k6k4o.png">x8</a>)|&#x1F87B; S / 1|||Modified
syndie6 (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/1shl71w3yy.png&after=http://img.taucetistation.org/32x32/forceresize/2tvs30q6k4.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/1shl71w3yy.png&after=http://img.taucetistation.org/128x128/forceresize/2tvs30q6k4.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/1shl71w3yy.png&after=http://img.taucetistation.org/256x256/forceresize/2tvs30q6k4.png">x8</a>)|&#x1F87B; S / 1|||Modified
ucig (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/sgkrb1l056.png&after=http://img.taucetistation.org/32x32/forceresize/doa7pny1nt.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/sgkrb1l056.png&after=http://img.taucetistation.org/128x128/forceresize/doa7pny1nt.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/sgkrb1l056.png&after=http://img.taucetistation.org/256x256/forceresize/doa7pny1nt.png">x8</a>)|&#x1F87B; S / 1|||Modified
ucig1 (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/8gp8tfhdh1.png&after=http://img.taucetistation.org/32x32/forceresize/0lmbdseipi.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/8gp8tfhdh1.png&after=http://img.taucetistation.org/128x128/forceresize/0lmbdseipi.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/8gp8tfhdh1.png&after=http://img.taucetistation.org/256x256/forceresize/0lmbdseipi.png">x8</a>)|&#x1F87B; S / 1|||Modified
ucig0 (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/mwhpjzn6db.png&after=http://img.taucetistation.org/32x32/forceresize/5exh0n4gfp.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/mwhpjzn6db.png&after=http://img.taucetistation.org/128x128/forceresize/5exh0n4gfp.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/mwhpjzn6db.png&after=http://img.taucetistation.org/256x256/forceresize/5exh0n4gfp.png">x8</a>)|&#x1F87B; S / 1|||Modified
Dpacket5 (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/l5ykbuod4b.png&after=http://img.taucetistation.org/32x32/forceresize/336ifkst7y.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/l5ykbuod4b.png&after=http://img.taucetistation.org/128x128/forceresize/336ifkst7y.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/l5ykbuod4b.png&after=http://img.taucetistation.org/256x256/forceresize/336ifkst7y.png">x8</a>)|&#x1F87B; S / 1|||Modified
syndie0 (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/jzsvrczy3v.png&after=http://img.taucetistation.org/32x32/forceresize/v5s20wgn41.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/jzsvrczy3v.png&after=http://img.taucetistation.org/128x128/forceresize/v5s20wgn41.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/jzsvrczy3v.png&after=http://img.taucetistation.org/256x256/forceresize/v5s20wgn41.png">x8</a>)|&#x1F87B; S / 1|||Modified
Dpacket4 (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/yh1v8vlk5b.png&after=http://img.taucetistation.org/32x32/forceresize/5pl3q8iq45.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/yh1v8vlk5b.png&after=http://img.taucetistation.org/128x128/forceresize/5pl3q8iq45.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/yh1v8vlk5b.png&after=http://img.taucetistation.org/256x256/forceresize/5pl3q8iq45.png">x8</a>)|&#x1F87B; S / 1|||Modified
syndie1 (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/4u0nlewk7f.png&after=http://img.taucetistation.org/32x32/forceresize/gwqv00zir0.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/4u0nlewk7f.png&after=http://img.taucetistation.org/128x128/forceresize/gwqv00zir0.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/4u0nlewk7f.png&after=http://img.taucetistation.org/256x256/forceresize/gwqv00zir0.png">x8</a>)|&#x1F87B; S / 1|||Modified
syndie2 (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/hvpy8xatye.png&after=http://img.taucetistation.org/32x32/forceresize/yevolyyg82.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/hvpy8xatye.png&after=http://img.taucetistation.org/128x128/forceresize/yevolyyg82.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/hvpy8xatye.png&after=http://img.taucetistation.org/256x256/forceresize/yevolyyg82.png">x8</a>)|&#x1F87B; S / 1|||Modified
Dpacket6 (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/rxxgop4hmg.png&after=http://img.taucetistation.org/32x32/forceresize/ey15qvje9j.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/rxxgop4hmg.png&after=http://img.taucetistation.org/128x128/forceresize/ey15qvje9j.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/rxxgop4hmg.png&after=http://img.taucetistation.org/256x256/forceresize/ey15qvje9j.png">x8</a>)|&#x1F87B; S / 1|||Modified
syndie3 (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/mwvwg5ofx1.png&after=http://img.taucetistation.org/32x32/forceresize/ck1h2m089j.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/mwvwg5ofx1.png&after=http://img.taucetistation.org/128x128/forceresize/ck1h2m089j.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/mwvwg5ofx1.png&after=http://img.taucetistation.org/256x256/forceresize/ck1h2m089j.png">x8</a>)|&#x1F87B; S / 1|||Modified
syndie (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/p48d4jl7fn.png&after=http://img.taucetistation.org/32x32/forceresize/irczny0gc7.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/p48d4jl7fn.png&after=http://img.taucetistation.org/128x128/forceresize/irczny0gc7.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/p48d4jl7fn.png&after=http://img.taucetistation.org/256x256/forceresize/irczny0gc7.png">x8</a>)|&#x1F87B; S / 1|||Modified
cigpacket0 (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/6t1kogcuww.png&after=http://img.taucetistation.org/32x32/forceresize/0rd2e441oq.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/6t1kogcuww.png&after=http://img.taucetistation.org/128x128/forceresize/0rd2e441oq.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/6t1kogcuww.png&after=http://img.taucetistation.org/256x256/forceresize/0rd2e441oq.png">x8</a>)|&#x1F87B; S / 1|||Modified
cigpacket5 (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/a5wcc17y56.png&after=http://img.taucetistation.org/32x32/forceresize/7sklc13we2.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/a5wcc17y56.png&after=http://img.taucetistation.org/128x128/forceresize/7sklc13we2.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/a5wcc17y56.png&after=http://img.taucetistation.org/256x256/forceresize/7sklc13we2.png">x8</a>)|&#x1F87B; S / 1|||Modified
cigpacket6 (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/qbhh35uzs0.png&after=http://img.taucetistation.org/32x32/forceresize/haqlbl4pla.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/qbhh35uzs0.png&after=http://img.taucetistation.org/128x128/forceresize/haqlbl4pla.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/qbhh35uzs0.png&after=http://img.taucetistation.org/256x256/forceresize/haqlbl4pla.png">x8</a>)|&#x1F87B; S / 1|||Modified
cigpacket3 (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/4fhjcg1do0.png&after=http://img.taucetistation.org/32x32/forceresize/t1hz79v2v0.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/4fhjcg1do0.png&after=http://img.taucetistation.org/128x128/forceresize/t1hz79v2v0.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/4fhjcg1do0.png&after=http://img.taucetistation.org/256x256/forceresize/t1hz79v2v0.png">x8</a>)|&#x1F87B; S / 1|||Modified
cigpacket4 (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/rc20honztd.png&after=http://img.taucetistation.org/32x32/forceresize/v1p1bmg1j7.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/rc20honztd.png&after=http://img.taucetistation.org/128x128/forceresize/v1p1bmg1j7.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/rc20honztd.png&after=http://img.taucetistation.org/256x256/forceresize/v1p1bmg1j7.png">x8</a>)|&#x1F87B; S / 1|||Modified
cigpacket1 (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/77c4ninby9.png&after=http://img.taucetistation.org/32x32/forceresize/fudc1qkbcl.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/77c4ninby9.png&after=http://img.taucetistation.org/128x128/forceresize/fudc1qkbcl.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/77c4ninby9.png&after=http://img.taucetistation.org/256x256/forceresize/fudc1qkbcl.png">x8</a>)|&#x1F87B; S / 1|||Modified
cigpacket2 (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/aom2nl4cf2.png&after=http://img.taucetistation.org/32x32/forceresize/6yq89vkapt.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/aom2nl4cf2.png&after=http://img.taucetistation.org/128x128/forceresize/6yq89vkapt.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/aom2nl4cf2.png&after=http://img.taucetistation.org/256x256/forceresize/6yq89vkapt.png">x8</a>)|&#x1F87B; S / 1|||Modified

States number:
- **Old DMI:** 41
- **New DMI:** 41
<hr /></details>

**Comment by volas** [comment]
Старые как-то более разнообразны, и синдикат потерял свои фирменные цвета

**Comment by YulianR** [comment]
Если я правильно понял, то синдикат не потерял цвета, это и есть мягкий черный, с фиолетовым отливом ибо так цвета выглядят насыщеннее и круче. Если что, почти все спрайты валтера сделаны так же

**Comment by volas** [comment]
Основной цвет синдиката - красный, в новой он почти не заметен. 
http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/i7q4ctrgld.png&after=http://img.taucetistation.org/256x256/forceresize/4fogadnm9o.png
С текущим вариантом я бы сказал, что это скорее нанотразен или просто фирменный цвет станции 13.
И по остальным коробкам - сейчас видно что это разные марки - отличаются логотипы, обводки, рисунок. В новых будто это один производитель с разными линейками.

**Comment by WatlerJe** [comment]
У меня на столе лежала пачка Вайсрой красных и по мере рисования я их покуривал, их дизайн лег в спрайты.
Обычно у брендовых сиг есть линейка с разной крепость, типа Мальборо белый и красный, Винстуха синий и белый и т.д. Соответственно я решил сделать тоже самое разделяя пачки по крепости, а не по брендам.

 (Мак Демарко посветил оду этим сигам https://youtu.be/6bfTTeZOrs4).

**Comment by YulianR** [comment]
Скоро апдейтну

**Comment by YulianR** [comment]
dreamseeker_2018-07-01_10-07-17

Собсно вот скрин ингейм, из изменений в последнем коммите: новые спрайты теперь - один бренд, разные модели. (У них разное описание и все такое). Также переименовал синди-сигареты в Syndie Smokes, по аналогии с синди кейками и прочим.

**Comment by volas** [comment]
@YulianR отредактируй хотя бы чеинжлог для соответствия ПРу

**Comment by YulianR** [comment]
@volas изменил

**Comment by YulianR** [comment]
Так, скоро заново создам.

**Pull request closed without merging**
