### PR TITLE
Обновите SpacemanDMM до 1.4

### PR DESCRIPTION
**Pull request by spookydonut**
I am using google translate

## Описание изменений
Я исправлю все найденные проблемы

### CODE REVIEW

**Comment by TauKitty** [comment]
###### Changelog status: :radio_button: No changelog

**Comment by LudwigVonChesterfield** [comment]
this is what happens when tg's closed

**Comment by volas** [comment]
Thanks!

There are some encoding problems (win1251/unicode), dnm until 513.

**Comment by spookydonut** [comment]
> 
> 
> Thanks!
> 
> There are some encoding problems (win1251/unicode), dnm until 513.

you should merge this now it doesn't affect anything except travis checking.

**Comment by volas** [comment]
Rebased on master, thanks again. https://github.com/TauCetiStation/TauCetiClassic/compare/d4ac29f03ba0...4367c14fb12a

**Comment by spookydonut** [comment]
No problems!

**Pull request closed without merging**
