### PR TITLE
Легкие респрайты бюрократии с ТГ

### PR DESCRIPTION
**Pull request by Lexakr**
Лайтовый респрайт бюрократии без спорных печатей и с ящиком для бумаги не с ТГ, а с гунов

Поправленные шкафы в игре

Ящик:

Бюрократия (без печатей, перьевых ручек и бина):

:cl:
 - image: Новые спрайты бюрократии.

### CODE REVIEW

**Comment by TauKitty** [comment]
## DMI Diff Report

<details><summary>icons/obj/bureaucracy.dmi</summary><hr />

Key | Dir / Frame | Old | New | Status
--- | :---------: | --- | --- | ------
folder_paper (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/8hayoyrx4n.png&after=http://img.taucetistation.org/32x32/forceresize/2udumkdopl.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/8hayoyrx4n.png&after=http://img.taucetistation.org/128x128/forceresize/2udumkdopl.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/8hayoyrx4n.png&after=http://img.taucetistation.org/256x256/forceresize/2udumkdopl.png">x8</a>)|&#x1F87B; S / 1|||Modified
paper_bin1 (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/smegs5t63t.png&after=http://img.taucetistation.org/32x32/forceresize/i6op4af88x.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/smegs5t63t.png&after=http://img.taucetistation.org/128x128/forceresize/i6op4af88x.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/smegs5t63t.png&after=http://img.taucetistation.org/256x256/forceresize/i6op4af88x.png">x8</a>)|&#x1F87B; S / 1|||Modified
paper_bin0 (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/5kemu4478r.png&after=http://img.taucetistation.org/32x32/forceresize/5t3ajff713.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/5kemu4478r.png&after=http://img.taucetistation.org/128x128/forceresize/5t3ajff713.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/5kemu4478r.png&after=http://img.taucetistation.org/256x256/forceresize/5t3ajff713.png">x8</a>)|&#x1F87B; S / 1|||Modified
paper_stack_words (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/ognbjl19xl.png&after=http://img.taucetistation.org/32x32/forceresize/e5plsn059l.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/ognbjl19xl.png&after=http://img.taucetistation.org/128x128/forceresize/e5plsn059l.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/ognbjl19xl.png&after=http://img.taucetistation.org/256x256/forceresize/e5plsn059l.png">x8</a>)|&#x1F87B; S / 1|||Modified
labeler1 (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/pxzr99hcfz.png&after=http://img.taucetistation.org/32x32/forceresize/2sppg7aql9.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/pxzr99hcfz.png&after=http://img.taucetistation.org/128x128/forceresize/2sppg7aql9.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/pxzr99hcfz.png&after=http://img.taucetistation.org/256x256/forceresize/2sppg7aql9.png">x8</a>)|&#x1F87B; S / 1|||Modified
clipboard (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/8i14eja9w4.png&after=http://img.taucetistation.org/32x32/forceresize/ta2dqpy9dt.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/8i14eja9w4.png&after=http://img.taucetistation.org/128x128/forceresize/ta2dqpy9dt.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/8i14eja9w4.png&after=http://img.taucetistation.org/256x256/forceresize/ta2dqpy9dt.png">x8</a>)|&#x1F87B; S / 1|||Modified
chestdrawer-open (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/dfcs2keq74.png&after=http://img.taucetistation.org/32x32/forceresize/auutmqcoif.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/dfcs2keq74.png&after=http://img.taucetistation.org/128x128/forceresize/auutmqcoif.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/dfcs2keq74.png&after=http://img.taucetistation.org/256x256/forceresize/auutmqcoif.png">x8</a>)|&#x1F87B; S / 1|||Modified
labeler0 (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/rrl02ehetc.png&after=http://img.taucetistation.org/32x32/forceresize/sxxdekhfbl.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/rrl02ehetc.png&after=http://img.taucetistation.org/128x128/forceresize/sxxdekhfbl.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/rrl02ehetc.png&after=http://img.taucetistation.org/256x256/forceresize/sxxdekhfbl.png">x8</a>)|&#x1F87B; S / 1|||Modified
pen (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/v32cd4734u.png&after=http://img.taucetistation.org/32x32/forceresize/97eplttbo9.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/v32cd4734u.png&after=http://img.taucetistation.org/128x128/forceresize/97eplttbo9.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/v32cd4734u.png&after=http://img.taucetistation.org/256x256/forceresize/97eplttbo9.png">x8</a>)|&#x1F87B; S / 1|||Modified
tallcabinet-open (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/9gferr7xqv.png&after=http://img.taucetistation.org/32x32/forceresize/ngmtrkzugt.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/9gferr7xqv.png&after=http://img.taucetistation.org/128x128/forceresize/ngmtrkzugt.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/9gferr7xqv.png&after=http://img.taucetistation.org/256x256/forceresize/ngmtrkzugt.png">x8</a>)|&#x1F87B; S / 1|||Modified
folder_blue (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/pi1sfhl59k.png&after=http://img.taucetistation.org/32x32/forceresize/8ma25znxye.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/pi1sfhl59k.png&after=http://img.taucetistation.org/128x128/forceresize/8ma25znxye.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/pi1sfhl59k.png&after=http://img.taucetistation.org/256x256/forceresize/8ma25znxye.png">x8</a>)|&#x1F87B; S / 1|||Modified
pamphlet (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/7xd3fbkoi7.png&after=http://img.taucetistation.org/32x32/forceresize/mhqzeese8u.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/7xd3fbkoi7.png&after=http://img.taucetistation.org/128x128/forceresize/mhqzeese8u.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/7xd3fbkoi7.png&after=http://img.taucetistation.org/256x256/forceresize/mhqzeese8u.png">x8</a>)|&#x1F87B; S / 1|||Modified
scrap_bloodied (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/x4rp8ispkg.png&after=http://img.taucetistation.org/32x32/forceresize/rr42qbsm2a.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/x4rp8ispkg.png&after=http://img.taucetistation.org/128x128/forceresize/rr42qbsm2a.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/x4rp8ispkg.png&after=http://img.taucetistation.org/256x256/forceresize/rr42qbsm2a.png">x8</a>)|&#x1F87B; S / 1|||Modified
clipboard_pen (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/ftd4m9ektz.png&after=http://img.taucetistation.org/32x32/forceresize/pcw4xujdbg.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/ftd4m9ektz.png&after=http://img.taucetistation.org/128x128/forceresize/pcw4xujdbg.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/ftd4m9ektz.png&after=http://img.taucetistation.org/256x256/forceresize/pcw4xujdbg.png">x8</a>)|&#x1F87B; S / 1|||Modified
pen_red (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/wawigiimkg.png&after=http://img.taucetistation.org/32x32/forceresize/eu2o5w1d0e.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/wawigiimkg.png&after=http://img.taucetistation.org/128x128/forceresize/eu2o5w1d0e.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/wawigiimkg.png&after=http://img.taucetistation.org/256x256/forceresize/eu2o5w1d0e.png">x8</a>)|&#x1F87B; S / 1|||Modified
filingcabinet (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/xk3uytothv.png&after=http://img.taucetistation.org/32x32/forceresize/ut27so6kpc.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/xk3uytothv.png&after=http://img.taucetistation.org/128x128/forceresize/ut27so6kpc.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/xk3uytothv.png&after=http://img.taucetistation.org/256x256/forceresize/ut27so6kpc.png">x8</a>)|&#x1F87B; S / 1|||Modified
folder (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/7ulxffanvy.png&after=http://img.taucetistation.org/32x32/forceresize/q35234sba4.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/7ulxffanvy.png&after=http://img.taucetistation.org/128x128/forceresize/q35234sba4.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/7ulxffanvy.png&after=http://img.taucetistation.org/256x256/forceresize/q35234sba4.png">x8</a>)|&#x1F87B; S / 1|||Modified
pen_blue (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/ccfrx7fxsv.png&after=http://img.taucetistation.org/32x32/forceresize/dz3fbrn0bq.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/ccfrx7fxsv.png&after=http://img.taucetistation.org/128x128/forceresize/dz3fbrn0bq.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/ccfrx7fxsv.png&after=http://img.taucetistation.org/256x256/forceresize/dz3fbrn0bq.png">x8</a>)|&#x1F87B; S / 1|||Modified
paper_words (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/8w0dv1n3vq.png&after=http://img.taucetistation.org/32x32/forceresize/r7xe4vvsbe.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/8w0dv1n3vq.png&after=http://img.taucetistation.org/128x128/forceresize/r7xe4vvsbe.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/8w0dv1n3vq.png&after=http://img.taucetistation.org/256x256/forceresize/r7xe4vvsbe.png">x8</a>)|&#x1F87B; S / 1|||Modified
folder_yellow (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/5328rz6tf7.png&after=http://img.taucetistation.org/32x32/forceresize/icys9xcrss.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/5328rz6tf7.png&after=http://img.taucetistation.org/128x128/forceresize/icys9xcrss.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/5328rz6tf7.png&after=http://img.taucetistation.org/256x256/forceresize/icys9xcrss.png">x8</a>)|&#x1F87B; S / 1|||Modified
newspaper (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/gcd2pe8ogv.png&after=http://img.taucetistation.org/32x32/forceresize/xr028qkvod.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/gcd2pe8ogv.png&after=http://img.taucetistation.org/128x128/forceresize/xr028qkvod.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/gcd2pe8ogv.png&after=http://img.taucetistation.org/256x256/forceresize/xr028qkvod.png">x8</a>)|&#x1F87B; S / 1|||Modified
filingcabinet-open (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/15myxenitb.png&after=http://img.taucetistation.org/32x32/forceresize/r6hlixn67b.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/15myxenitb.png&after=http://img.taucetistation.org/128x128/forceresize/r6hlixn67b.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/15myxenitb.png&after=http://img.taucetistation.org/256x256/forceresize/r6hlixn67b.png">x8</a>)|&#x1F87B; S / 1|||Modified
paper_talisman (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/pzg0bpkazv.png&after=http://img.taucetistation.org/32x32/forceresize/aps1j5ht6h.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/pzg0bpkazv.png&after=http://img.taucetistation.org/128x128/forceresize/aps1j5ht6h.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/pzg0bpkazv.png&after=http://img.taucetistation.org/256x256/forceresize/aps1j5ht6h.png">x8</a>)|&#x1F87B; S / 1|||Modified
paper_stack (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/3hy57pfin1.png&after=http://img.taucetistation.org/32x32/forceresize/bqrah851mt.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/3hy57pfin1.png&after=http://img.taucetistation.org/128x128/forceresize/bqrah851mt.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/3hy57pfin1.png&after=http://img.taucetistation.org/256x256/forceresize/bqrah851mt.png">x8</a>)|&#x1F87B; S / 1|||Modified
folder_white (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/2f7k335nxv.png&after=http://img.taucetistation.org/32x32/forceresize/n25f3cbt1g.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/2f7k335nxv.png&after=http://img.taucetistation.org/128x128/forceresize/n25f3cbt1g.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/2f7k335nxv.png&after=http://img.taucetistation.org/256x256/forceresize/n25f3cbt1g.png">x8</a>)|&#x1F87B; S / 1|||Modified
scrap (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/k4dzqoq7lq.png&after=http://img.taucetistation.org/32x32/forceresize/9jtekxj7m5.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/k4dzqoq7lq.png&after=http://img.taucetistation.org/128x128/forceresize/9jtekxj7m5.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/k4dzqoq7lq.png&after=http://img.taucetistation.org/256x256/forceresize/9jtekxj7m5.png">x8</a>)|&#x1F87B; S / 1|||Modified
paper (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/8ag0oztyek.png&after=http://img.taucetistation.org/32x32/forceresize/7yspcu6sj0.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/8ag0oztyek.png&after=http://img.taucetistation.org/128x128/forceresize/7yspcu6sj0.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/8ag0oztyek.png&after=http://img.taucetistation.org/256x256/forceresize/7yspcu6sj0.png">x8</a>)|&#x1F87B; S / 1|||Modified
pen_blink (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/v32cd4734u.png&after=http://img.taucetistation.org/32x32/forceresize/97eplttbo9.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/v32cd4734u.png&after=http://img.taucetistation.org/128x128/forceresize/97eplttbo9.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/v32cd4734u.png&after=http://img.taucetistation.org/256x256/forceresize/97eplttbo9.png">x8</a>)|&#x1F87B; S / 1|||Modified
pen_blink (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/tteijwm23w.png&after=http://img.taucetistation.org/32x32/forceresize/0t08tdehim.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/tteijwm23w.png&after=http://img.taucetistation.org/128x128/forceresize/0t08tdehim.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/tteijwm23w.png&after=http://img.taucetistation.org/256x256/forceresize/0t08tdehim.png">x8</a>)|&#x1F87B; S / 2|||Modified
folder_red (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/91mz92wt3r.png&after=http://img.taucetistation.org/32x32/forceresize/bc289ck175.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/91mz92wt3r.png&after=http://img.taucetistation.org/128x128/forceresize/bc289ck175.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/91mz92wt3r.png&after=http://img.taucetistation.org/256x256/forceresize/bc289ck175.png">x8</a>)|&#x1F87B; S / 1|||Modified
chestdrawer (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/rzp3i4ya4e.png&after=http://img.taucetistation.org/32x32/forceresize/djrc9hqcm5.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/rzp3i4ya4e.png&after=http://img.taucetistation.org/128x128/forceresize/djrc9hqcm5.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/rzp3i4ya4e.png&after=http://img.taucetistation.org/256x256/forceresize/djrc9hqcm5.png">x8</a>)|&#x1F87B; S / 1|||Modified
alienpaper_words (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/eovaceyc2l.png&after=http://img.taucetistation.org/32x32/forceresize/854jxqs5il.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/eovaceyc2l.png&after=http://img.taucetistation.org/128x128/forceresize/854jxqs5il.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/eovaceyc2l.png&after=http://img.taucetistation.org/256x256/forceresize/854jxqs5il.png">x8</a>)|&#x1F87B; S / 1|||Modified
clipboard_over (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/2da2py1svl.png&after=http://img.taucetistation.org/32x32/forceresize/l2xolxtmsz.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/2da2py1svl.png&after=http://img.taucetistation.org/128x128/forceresize/l2xolxtmsz.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/2da2py1svl.png&after=http://img.taucetistation.org/256x256/forceresize/l2xolxtmsz.png">x8</a>)|&#x1F87B; S / 1|||Modified
tallcabinet (<a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/32x32/forceresize/a3b94garcj.png&after=http://img.taucetistation.org/32x32/forceresize/lgycy377dy.png">x1</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/128x128/forceresize/a3b94garcj.png&after=http://img.taucetistation.org/128x128/forceresize/lgycy377dy.png">x4</a> <a href="http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/a3b94garcj.png&after=http://img.taucetistation.org/256x256/forceresize/lgycy377dy.png">x8</a>)|&#x1F87B; S / 1|||Modified

States number:
- **Old DMI:** 70
- **New DMI:** 70
<hr /></details>

**Comment by Tolerantboy** [comment]
По мне так только ручки и печати нормально выглядят тут

**Comment by volas** [comment]
@SpaiR тут @TauKitty обновленные спрайты что-то не поймала

**Comment by volas** [comment]
@Lexakr 
Еще небольшие придирки.
img - сразу видно какая-то коробочка
img - непонятно что

Газета старая http://tauceti.ru/img-diff/?before=http://img.taucetistation.org/256x256/forceresize/gcd2pe8ogv.png&after=http://img.taucetistation.org/256x256/forceresize/xr028qkvod.png мне тоже как-то больше нравится и кажется понятней.
В остальном я не против. Но если спрайтеры одобряют это, мержу.

**Comment by volas** [comment]
Ок, Лексакр пообещал исправить потом

**Pull request merged**
