### PR TITLE
[Mirror]Маски четверки из payday

### PR DESCRIPTION
**Pull request by BoredFox**
**_That's a mirrored PR from repository https://github.com/GammaStation/Gamma-Station
Original PR: https://github.com/GammaStation/Gamma-Station/pull/121_**

:cl: UDaV73rus
 - image: Четыре новые маски из payday, можно получить в театральном вендомате

payday

### CODE REVIEW

**Comment by TauKitty** [comment]
## DMI Diff Report

<details><summary>icons/mob/inhands/clothing_lefthand.dmi <b><< duplicates</b></summary><hr>

**Warning!** States duplication detected:
- **Old DMI:** [syndicate-elite, fedora, chefhat, necromancer, helmet]
- **New DMI:** [syndicate-elite, fedora, chefhat, necromancer, helmet]

*Duplication of states may result into unpredictable behavior in game and incorrect diff report, so fix is recommended.*

Key|Dir / Frame|Old|New|Status
---|:---------:|---|---|------
hoxton_mask ([x1](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/32x32/forceresize/yjv4x1u3w9.png) [x4](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/128x128/forceresize/yjv4x1u3w9.png) [x8](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/256x256/forceresize/yjv4x1u3w9.png))|&#x1F87B; S / 1|||Created
hoxton_mask ([x1](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/32x32/forceresize/0tl3nvbdx3.png) [x4](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/128x128/forceresize/0tl3nvbdx3.png) [x8](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/256x256/forceresize/0tl3nvbdx3.png))|&#x1F879; N / 1|||Created
hoxton_mask ([x1](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/32x32/forceresize/ym82ektip8.png) [x4](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/128x128/forceresize/ym82ektip8.png) [x8](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/256x256/forceresize/ym82ektip8.png))|&#x1F87A; E / 1|||Created
hoxton_mask ([x1](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/32x32/forceresize/w4413tg0g7.png) [x4](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/128x128/forceresize/w4413tg0g7.png) [x8](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/256x256/forceresize/w4413tg0g7.png))|&#x1F878; W / 1|||Created
dallas_mask ([x1](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/32x32/forceresize/skxvjkpdlb.png) [x4](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/128x128/forceresize/skxvjkpdlb.png) [x8](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/256x256/forceresize/skxvjkpdlb.png))|&#x1F87B; S / 1|||Created
dallas_mask ([x1](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/32x32/forceresize/v947kg2qm0.png) [x4](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/128x128/forceresize/v947kg2qm0.png) [x8](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/256x256/forceresize/v947kg2qm0.png))|&#x1F879; N / 1|||Created
dallas_mask ([x1](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/32x32/forceresize/exmmhpnso4.png) [x4](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/128x128/forceresize/exmmhpnso4.png) [x8](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/256x256/forceresize/exmmhpnso4.png))|&#x1F87A; E / 1|||Created
dallas_mask ([x1](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/32x32/forceresize/36h7edf94m.png) [x4](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/128x128/forceresize/36h7edf94m.png) [x8](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/256x256/forceresize/36h7edf94m.png))|&#x1F878; W / 1|||Created
chains_mask ([x1](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/32x32/forceresize/hwouab51yg.png) [x4](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/128x128/forceresize/hwouab51yg.png) [x8](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/256x256/forceresize/hwouab51yg.png))|&#x1F87B; S / 1|||Created
chains_mask ([x1](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/32x32/forceresize/oynug27qzr.png) [x4](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/128x128/forceresize/oynug27qzr.png) [x8](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/256x256/forceresize/oynug27qzr.png))|&#x1F879; N / 1|||Created
chains_mask ([x1](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/32x32/forceresize/ym82ektip8.png) [x4](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/128x128/forceresize/ym82ektip8.png) [x8](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/256x256/forceresize/ym82ektip8.png))|&#x1F87A; E / 1|||Created
chains_mask ([x1](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/32x32/forceresize/w7cy9o0luk.png) [x4](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/128x128/forceresize/w7cy9o0luk.png) [x8](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/256x256/forceresize/w7cy9o0luk.png))|&#x1F878; W / 1|||Created
wolf_mask ([x1](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/32x32/forceresize/fs2avrtqm2.png) [x4](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/128x128/forceresize/fs2avrtqm2.png) [x8](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/256x256/forceresize/fs2avrtqm2.png))|&#x1F87B; S / 1|||Created
wolf_mask ([x1](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/32x32/forceresize/haevl3sfq8.png) [x4](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/128x128/forceresize/haevl3sfq8.png) [x8](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/256x256/forceresize/haevl3sfq8.png))|&#x1F879; N / 1|||Created
wolf_mask ([x1](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/32x32/forceresize/ym82ektip8.png) [x4](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/128x128/forceresize/ym82ektip8.png) [x8](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/256x256/forceresize/ym82ektip8.png))|&#x1F87A; E / 1|||Created
wolf_mask ([x1](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/32x32/forceresize/jf8iygm03x.png) [x4](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/128x128/forceresize/jf8iygm03x.png) [x8](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/256x256/forceresize/jf8iygm03x.png))|&#x1F878; W / 1|||Created

States number:
- **Old DMI:** 219
- **New DMI:** 223
<hr></details><details><summary>icons/mob/inhands/clothing_righthand.dmi <b><< duplicates</b></summary><hr>

**Warning!** States duplication detected:
- **Old DMI:** [fedora, chefhat, necromancer, helmet]
- **New DMI:** [fedora, chefhat, necromancer, helmet]

*Duplication of states may result into unpredictable behavior in game and incorrect diff report, so fix is recommended.*

Key|Dir / Frame|Old|New|Status
---|:---------:|---|---|------
hoxton_mask ([x1](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/32x32/forceresize/0tl3nvbdx3.png) [x4](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/128x128/forceresize/0tl3nvbdx3.png) [x8](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/256x256/forceresize/0tl3nvbdx3.png))|&#x1F87B; S / 1|||Created
hoxton_mask ([x1](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/32x32/forceresize/yjv4x1u3w9.png) [x4](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/128x128/forceresize/yjv4x1u3w9.png) [x8](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/256x256/forceresize/yjv4x1u3w9.png))|&#x1F879; N / 1|||Created
hoxton_mask ([x1](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/32x32/forceresize/kdmudtaxbf.png) [x4](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/128x128/forceresize/kdmudtaxbf.png) [x8](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/256x256/forceresize/kdmudtaxbf.png))|&#x1F87A; E / 1|||Created
hoxton_mask ([x1](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/32x32/forceresize/o4ywgtnhsd.png) [x4](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/128x128/forceresize/o4ywgtnhsd.png) [x8](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/256x256/forceresize/o4ywgtnhsd.png))|&#x1F878; W / 1|||Created
dallas_mask ([x1](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/32x32/forceresize/v947kg2qm0.png) [x4](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/128x128/forceresize/v947kg2qm0.png) [x8](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/256x256/forceresize/v947kg2qm0.png))|&#x1F87B; S / 1|||Created
dallas_mask ([x1](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/32x32/forceresize/skxvjkpdlb.png) [x4](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/128x128/forceresize/skxvjkpdlb.png) [x8](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/256x256/forceresize/skxvjkpdlb.png))|&#x1F879; N / 1|||Created
dallas_mask ([x1](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/32x32/forceresize/8047q5wawd.png) [x4](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/128x128/forceresize/8047q5wawd.png) [x8](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/256x256/forceresize/8047q5wawd.png))|&#x1F87A; E / 1|||Created
dallas_mask ([x1](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/32x32/forceresize/i3megvepu5.png) [x4](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/128x128/forceresize/i3megvepu5.png) [x8](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/256x256/forceresize/i3megvepu5.png))|&#x1F878; W / 1|||Created
chains_mask ([x1](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/32x32/forceresize/oynug27qzr.png) [x4](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/128x128/forceresize/oynug27qzr.png) [x8](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/256x256/forceresize/oynug27qzr.png))|&#x1F87B; S / 1|||Created
chains_mask ([x1](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/32x32/forceresize/hwouab51yg.png) [x4](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/128x128/forceresize/hwouab51yg.png) [x8](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/256x256/forceresize/hwouab51yg.png))|&#x1F879; N / 1|||Created
chains_mask ([x1](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/32x32/forceresize/tazm8glt1w.png) [x4](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/128x128/forceresize/tazm8glt1w.png) [x8](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/256x256/forceresize/tazm8glt1w.png))|&#x1F87A; E / 1|||Created
chains_mask ([x1](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/32x32/forceresize/o4ywgtnhsd.png) [x4](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/128x128/forceresize/o4ywgtnhsd.png) [x8](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/256x256/forceresize/o4ywgtnhsd.png))|&#x1F878; W / 1|||Created
wolf_mask ([x1](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/32x32/forceresize/haevl3sfq8.png) [x4](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/128x128/forceresize/haevl3sfq8.png) [x8](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/256x256/forceresize/haevl3sfq8.png))|&#x1F87B; S / 1|||Created
wolf_mask ([x1](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/32x32/forceresize/fs2avrtqm2.png) [x4](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/128x128/forceresize/fs2avrtqm2.png) [x8](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/256x256/forceresize/fs2avrtqm2.png))|&#x1F879; N / 1|||Created
wolf_mask ([x1](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/32x32/forceresize/p405o31ag5.png) [x4](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/128x128/forceresize/p405o31ag5.png) [x8](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/256x256/forceresize/p405o31ag5.png))|&#x1F87A; E / 1|||Created
wolf_mask ([x1](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/32x32/forceresize/o4ywgtnhsd.png) [x4](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/128x128/forceresize/o4ywgtnhsd.png) [x8](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/256x256/forceresize/o4ywgtnhsd.png))|&#x1F878; W / 1|||Created

States number:
- **Old DMI:** 218
- **New DMI:** 222
<hr></details><details><summary>icons/mob/mask.dmi</summary><hr>


Key|Dir / Frame|Old|New|Status
---|:---------:|---|---|------
dallas ([x1](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/32x32/forceresize/4lknqw8ypv.png) [x4](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/128x128/forceresize/4lknqw8ypv.png) [x8](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/256x256/forceresize/4lknqw8ypv.png))|&#x1F87B; S / 1|||Created
dallas ([x1](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/32x32/forceresize/m19z52k6je.png) [x4](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/128x128/forceresize/m19z52k6je.png) [x8](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/256x256/forceresize/m19z52k6je.png))|&#x1F879; N / 1|||Created
dallas ([x1](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/32x32/forceresize/zzix7lii2l.png) [x4](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/128x128/forceresize/zzix7lii2l.png) [x8](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/256x256/forceresize/zzix7lii2l.png))|&#x1F87A; E / 1|||Created
dallas ([x1](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/32x32/forceresize/daxn4e8kci.png) [x4](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/128x128/forceresize/daxn4e8kci.png) [x8](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/256x256/forceresize/daxn4e8kci.png))|&#x1F878; W / 1|||Created
chains ([x1](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/32x32/forceresize/wiq2dsz7lr.png) [x4](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/128x128/forceresize/wiq2dsz7lr.png) [x8](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/256x256/forceresize/wiq2dsz7lr.png))|&#x1F87B; S / 1|||Created
chains ([x1](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/32x32/forceresize/m19z52k6je.png) [x4](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/128x128/forceresize/m19z52k6je.png) [x8](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/256x256/forceresize/m19z52k6je.png))|&#x1F879; N / 1|||Created
chains ([x1](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/32x32/forceresize/di75b7dwf3.png) [x4](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/128x128/forceresize/di75b7dwf3.png) [x8](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/256x256/forceresize/di75b7dwf3.png))|&#x1F87A; E / 1|||Created
chains ([x1](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/32x32/forceresize/wimrbaw70q.png) [x4](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/128x128/forceresize/wimrbaw70q.png) [x8](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/256x256/forceresize/wimrbaw70q.png))|&#x1F878; W / 1|||Created
hoxton ([x1](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/32x32/forceresize/pdv96b4joo.png) [x4](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/128x128/forceresize/pdv96b4joo.png) [x8](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/256x256/forceresize/pdv96b4joo.png))|&#x1F87B; S / 1|||Created
hoxton ([x1](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/32x32/forceresize/m19z52k6je.png) [x4](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/128x128/forceresize/m19z52k6je.png) [x8](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/256x256/forceresize/m19z52k6je.png))|&#x1F879; N / 1|||Created
hoxton ([x1](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/32x32/forceresize/w6lgmi7cpx.png) [x4](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/128x128/forceresize/w6lgmi7cpx.png) [x8](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/256x256/forceresize/w6lgmi7cpx.png))|&#x1F87A; E / 1|||Created
hoxton ([x1](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/32x32/forceresize/szzotdwbqq.png) [x4](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/128x128/forceresize/szzotdwbqq.png) [x8](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/256x256/forceresize/szzotdwbqq.png))|&#x1F878; W / 1|||Created
wolf ([x1](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/32x32/forceresize/q3be1owed3.png) [x4](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/128x128/forceresize/q3be1owed3.png) [x8](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/256x256/forceresize/q3be1owed3.png))|&#x1F87B; S / 1|||Created
wolf ([x1](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/32x32/forceresize/m19z52k6je.png) [x4](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/128x128/forceresize/m19z52k6je.png) [x8](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/256x256/forceresize/m19z52k6je.png))|&#x1F879; N / 1|||Created
wolf ([x1](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/32x32/forceresize/ip2c7xq2zt.png) [x4](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/128x128/forceresize/ip2c7xq2zt.png) [x8](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/256x256/forceresize/ip2c7xq2zt.png))|&#x1F87A; E / 1|||Created
wolf ([x1](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/32x32/forceresize/wjbbc3u2xc.png) [x4](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/128x128/forceresize/wjbbc3u2xc.png) [x8](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/256x256/forceresize/wjbbc3u2xc.png))|&#x1F878; W / 1|||Created

States number:
- **Old DMI:** 89
- **New DMI:** 93
<hr></details><details><summary>icons/obj/clothing/masks.dmi <b><< duplicates</b></summary><hr>

**Warning!** States duplication detected:
- **Old DMI:** []
- **New DMI:** []

*Duplication of states may result into unpredictable behavior in game and incorrect diff report, so fix is recommended.*

Key|Dir / Frame|Old|New|Status
---|:---------:|---|---|------
dallas ([x1](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/32x32/forceresize/cf7m1er6ao.png) [x4](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/128x128/forceresize/cf7m1er6ao.png) [x8](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/256x256/forceresize/cf7m1er6ao.png))|&#x1F87B; S / 1|||Created
chains ([x1](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/32x32/forceresize/oy9eh1x1n2.png) [x4](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/128x128/forceresize/oy9eh1x1n2.png) [x8](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/256x256/forceresize/oy9eh1x1n2.png))|&#x1F87B; S / 1|||Created
hoxton ([x1](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/32x32/forceresize/ydg65w6lyb.png) [x4](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/128x128/forceresize/ydg65w6lyb.png) [x8](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/256x256/forceresize/ydg65w6lyb.png))|&#x1F87B; S / 1|||Created
wolf ([x1](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/32x32/forceresize/vntyby6se3.png) [x4](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/128x128/forceresize/vntyby6se3.png) [x8](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/256x256/forceresize/vntyby6se3.png))|&#x1F87B; S / 1|||Created

States number:
- **Old DMI:** 85
- **New DMI:** 89
<hr></details>

**Comment by volas** [comment]
В диффе много каких-то левых изменений в ``masks.dmi`` (@hitsedesen всё сломал, не иначе)

**Comment by volas** [comment]
Ну и по маскам, мне кажется стремно выглядят.

**Comment by RichardJones1** [comment]
Решим позже по ним, я потом буду подчищать спрайты одежды, портируя новую. Возьму скорее всего эти маски туда, переговорим. Может даже дело дойдет до голосования на форуме?

Вообщем, я, честно, не вижу смысла держать ПР открытым и возьму на себя смелость его закрыть.

**Pull request closed without merging**
