### PR TITLE
Респрайт инженерных беретов.

### PR DESCRIPTION
**Pull request by RichardJones1**
:cl: Richard Jones
 - image: Изменен спрайт инженерного берета.

### CODE REVIEW

**Comment by TauKitty** [comment]
## DMI Diff Report

<details><summary>icons/mob/head.dmi</summary><hr>


Key|Dir / Frame|Old|New|Status
---|:---------:|---|---|------
rig0-cmo ([x1](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/32x32/forceresize/z7e9k35wby.png) [x4](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/128x128/forceresize/z7e9k35wby.png) [x8](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/256x256/forceresize/z7e9k35wby.png))|🡻 S / 1|||Deleted
rig0-cmo ([x1](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/32x32/forceresize/40paz6lzyf.png) [x4](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/128x128/forceresize/40paz6lzyf.png) [x8](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/256x256/forceresize/40paz6lzyf.png))|🡹 N / 1|||Deleted
rig0-cmo ([x1](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/32x32/forceresize/n9123nvx2k.png) [x4](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/128x128/forceresize/n9123nvx2k.png) [x8](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/256x256/forceresize/n9123nvx2k.png))|🡺 E / 1|||Deleted
rig0-cmo ([x1](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/32x32/forceresize/6qihxb6slv.png) [x4](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/128x128/forceresize/6qihxb6slv.png) [x8](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/256x256/forceresize/6qihxb6slv.png))|🡸 W / 1|||Deleted
rig1-hos ([x1](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/32x32/forceresize/zvc7mlyynv.png) [x4](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/128x128/forceresize/zvc7mlyynv.png) [x8](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/256x256/forceresize/zvc7mlyynv.png))|🡻 S / 1|||Deleted
rig1-hos ([x1](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/32x32/forceresize/qoku0n41uf.png) [x4](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/128x128/forceresize/qoku0n41uf.png) [x8](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/256x256/forceresize/qoku0n41uf.png))|🡹 N / 1|||Deleted
rig1-hos ([x1](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/32x32/forceresize/dbnf4j5k18.png) [x4](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/128x128/forceresize/dbnf4j5k18.png) [x8](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/256x256/forceresize/dbnf4j5k18.png))|🡺 E / 1|||Deleted
rig1-hos ([x1](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/32x32/forceresize/gi92wi7jhj.png) [x4](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/128x128/forceresize/gi92wi7jhj.png) [x8](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/256x256/forceresize/gi92wi7jhj.png))|🡸 W / 1|||Deleted
rig0-hos ([x1](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/32x32/forceresize/ab5rz5w7ql.png) [x4](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/128x128/forceresize/ab5rz5w7ql.png) [x8](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/256x256/forceresize/ab5rz5w7ql.png))|🡻 S / 1|||Deleted
rig0-hos ([x1](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/32x32/forceresize/hm96j4h6cs.png) [x4](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/128x128/forceresize/hm96j4h6cs.png) [x8](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/256x256/forceresize/hm96j4h6cs.png))|🡹 N / 1|||Deleted
rig0-hos ([x1](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/32x32/forceresize/r3pdmc0kqd.png) [x4](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/128x128/forceresize/r3pdmc0kqd.png) [x8](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/256x256/forceresize/r3pdmc0kqd.png))|🡺 E / 1|||Deleted
rig0-hos ([x1](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/32x32/forceresize/o05wv3y116.png) [x4](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/128x128/forceresize/o05wv3y116.png) [x8](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/256x256/forceresize/o05wv3y116.png))|🡸 W / 1|||Deleted
cowboy_hat ([x1](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/32x32/forceresize/mur5wdbxuc.png&after=https://img.taucetistation.org/32x32/forceresize/ac9xhfwq5u.png) [x4](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/128x128/forceresize/mur5wdbxuc.png&after=https://img.taucetistation.org/128x128/forceresize/ac9xhfwq5u.png) [x8](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/256x256/forceresize/mur5wdbxuc.png&after=https://img.taucetistation.org/256x256/forceresize/ac9xhfwq5u.png))|🡻 S / 1|||Modified
cowboy_hat ([x1](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/32x32/forceresize/39rkwe8wt2.png&after=https://img.taucetistation.org/32x32/forceresize/ac9xhfwq5u.png) [x4](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/128x128/forceresize/39rkwe8wt2.png&after=https://img.taucetistation.org/128x128/forceresize/ac9xhfwq5u.png) [x8](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/256x256/forceresize/39rkwe8wt2.png&after=https://img.taucetistation.org/256x256/forceresize/ac9xhfwq5u.png))|🡹 N / 1|||Modified
cowboy_hat ([x1](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/32x32/forceresize/n1c1z4lohc.png&after=https://img.taucetistation.org/32x32/forceresize/z8mcg1z1k4.png) [x4](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/128x128/forceresize/n1c1z4lohc.png&after=https://img.taucetistation.org/128x128/forceresize/z8mcg1z1k4.png) [x8](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/256x256/forceresize/n1c1z4lohc.png&after=https://img.taucetistation.org/256x256/forceresize/z8mcg1z1k4.png))|🡺 E / 1|||Modified
cowboy_hat ([x1](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/32x32/forceresize/x1siplr0yg.png&after=https://img.taucetistation.org/32x32/forceresize/z38n5wccy6.png) [x4](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/128x128/forceresize/x1siplr0yg.png&after=https://img.taucetistation.org/128x128/forceresize/z38n5wccy6.png) [x8](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/256x256/forceresize/x1siplr0yg.png&after=https://img.taucetistation.org/256x256/forceresize/z38n5wccy6.png))|🡸 W / 1|||Modified
rig1-cmo ([x1](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/32x32/forceresize/9c4yzaehwh.png) [x4](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/128x128/forceresize/9c4yzaehwh.png) [x8](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/256x256/forceresize/9c4yzaehwh.png))|🡻 S / 1|||Deleted
rig1-cmo ([x1](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/32x32/forceresize/fuzxqqkblt.png) [x4](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/128x128/forceresize/fuzxqqkblt.png) [x8](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/256x256/forceresize/fuzxqqkblt.png))|🡹 N / 1|||Deleted
rig1-cmo ([x1](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/32x32/forceresize/8rj9d6fw20.png) [x4](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/128x128/forceresize/8rj9d6fw20.png) [x8](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/256x256/forceresize/8rj9d6fw20.png))|🡺 E / 1|||Deleted
rig1-cmo ([x1](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/32x32/forceresize/eg9278xgox.png) [x4](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/128x128/forceresize/eg9278xgox.png) [x8](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/256x256/forceresize/eg9278xgox.png))|🡸 W / 1|||Deleted
e_beret_badge ([x1](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/32x32/forceresize/w1whbnqnyy.png&after=https://img.taucetistation.org/32x32/forceresize/gf628abip2.png) [x4](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/128x128/forceresize/w1whbnqnyy.png&after=https://img.taucetistation.org/128x128/forceresize/gf628abip2.png) [x8](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/256x256/forceresize/w1whbnqnyy.png&after=https://img.taucetistation.org/256x256/forceresize/gf628abip2.png))|🡻 S / 1|||Modified
e_beret_badge ([x1](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/32x32/forceresize/rht4w1pwev.png&after=https://img.taucetistation.org/32x32/forceresize/5aqfm22rd8.png) [x4](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/128x128/forceresize/rht4w1pwev.png&after=https://img.taucetistation.org/128x128/forceresize/5aqfm22rd8.png) [x8](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/256x256/forceresize/rht4w1pwev.png&after=https://img.taucetistation.org/256x256/forceresize/5aqfm22rd8.png))|🡹 N / 1|||Modified
e_beret_badge ([x1](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/32x32/forceresize/0xh4peigur.png&after=https://img.taucetistation.org/32x32/forceresize/8anmrk3rfw.png) [x4](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/128x128/forceresize/0xh4peigur.png&after=https://img.taucetistation.org/128x128/forceresize/8anmrk3rfw.png) [x8](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/256x256/forceresize/0xh4peigur.png&after=https://img.taucetistation.org/256x256/forceresize/8anmrk3rfw.png))|🡺 E / 1|||Modified
e_beret_badge ([x1](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/32x32/forceresize/zfwlc4g8ya.png&after=https://img.taucetistation.org/32x32/forceresize/34mxzri819.png) [x4](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/128x128/forceresize/zfwlc4g8ya.png&after=https://img.taucetistation.org/128x128/forceresize/34mxzri819.png) [x8](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/256x256/forceresize/zfwlc4g8ya.png&after=https://img.taucetistation.org/256x256/forceresize/34mxzri819.png))|🡸 W / 1|||Modified
indiana_hat ([x1](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/32x32/forceresize/2p4l9aaoez.png&after=https://img.taucetistation.org/32x32/forceresize/cv7eqb1xvu.png) [x4](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/128x128/forceresize/2p4l9aaoez.png&after=https://img.taucetistation.org/128x128/forceresize/cv7eqb1xvu.png) [x8](http://tauceti.ru/img-diff/?before=https://img.taucetistation.org/256x256/forceresize/2p4l9aaoez.png&after=https://img.taucetistation.org/256x256/forceresize/cv7eqb1xvu.png))|🡻 S / 1|||Modified
cowboy ([x1](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/32x32/forceresize/1d51yk1arc.png) [x4](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/128x128/forceresize/1d51yk1arc.png) [x8](http://tauceti.ru/img-diff/?after=https://img.taucetistation.org/256x256/forceresize/1d51yk1arc.png))|🡻 S / 1|||Created

States number:
- **Old DMI:** 309
- **New DMI:** 306
<hr></details>

**Comment by RichardJones1** [comment]
Сейчас починю.

**Comment by RichardJones1** [comment]
Должно быть нормально.

**Comment by Belfogor** [comment]
[https://www.youtube.com/watch?v=umDr0mPuyQc](url)

**Comment by volas** [comment]
@RichardJones1 видимо использовался старый бранч за основу, попробуй на бранче
``git pull upstream master``
и, если всё ок,
``git push``

**Comment by RichardJones1** [comment]
Принято, думал, такое только с картой бывает

**Comment by RichardJones1** [comment]
test
По просьбам желающих

**Comment by AgRevol** [comment]
"По просьбам желающих"
@ 
Сам решил - сам сделал

**Comment by volas** [comment]
Это всё еще конфликтный ПР, вылови меня потом в дискорде

**Comment by RichardJones1** [comment]
Слава богам, я починил!

**Pull request merged**
